# Generated by Django 3.1.7 on 2021-04-15 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210415_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postrewiews',
            options={'ordering': ('-data',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы Блога'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='url',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, default='Админ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.category', verbose_name='Категория'),
        ),
    ]
