# Generated by Django 3.1.7 on 2021-04-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postrewiews_postid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrewiews',
            name='text',
            field=models.TextField(help_text='Максимум 1000 символов', max_length=1000, verbose_name='Сообщение'),
        ),
    ]
