# Generated by Django 3.1.7 on 2021-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210420_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='preview',
            field=models.CharField(blank=True, default='Какойто текст начала статьи', max_length=200, null=True),
        ),
    ]
