# Generated by Django 3.1.7 on 2021-04-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210422_1730'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryBlog',
        ),
    ]
