# Generated by Django 3.1.7 on 2021-04-15 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0003_auto_20210415_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_top',
            field=models.BooleanField(default=False, verbose_name='В новинках?'),
        ),
    ]
