# Generated by Django 3.1.7 on 2021-04-15 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0006_auto_20210415_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
