# Generated by Django 3.1.7 on 2021-04-20 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0007_auto_20210415_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiews',
            name='revId',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
