# Generated by Django 3.1.7 on 2021-04-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0008_rewiews_revid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_online',
            field=models.CharField(blank=True, default='None', max_length=255, null=True, verbose_name='Статус онлайн оплаты'),
        ),
    ]
