# Generated by Django 3.1.7 on 2021-04-22 14:29

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0009_auto_20210421_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='adress',
            field=models.CharField(default=1, max_length=60, verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(default=1, max_length=60, verbose_name='Емайл'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='otdel',
            field=models.CharField(default=1, max_length=20, verbose_name='Отделение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=98, size=[800, 500], upload_to='images/photos/%Y/%m/%d/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=98, size=[800, 500], upload_to='images/photos/%Y/%m/%d/', verbose_name='изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=98, size=[800, 500], upload_to='images/photos/%Y/%m/%d/', verbose_name='изображение 3'),
        ),
    ]
