# Generated by Django 3.1.7 on 2021-04-22 19:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0011_auto_20210422_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name=' Номер телефона'),
        ),
    ]
