# Generated by Django 3.1.7 on 2021-04-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('len_parfume', '0012_auto_20210422_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
    ]
